// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? 'AIzaSyDe50SY2mD3wnKlFehdVyckhN3_HC3MmJs',
    appId: dotenv.env['FIREBASE_ANDROID_APP_ID'] ?? '1:712998131650:android:3b603c0f834ee795dd685b',
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '712998131650',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'govease-keshara',
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'govease-keshara.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? 'AIzaSyAoXjgy8LM7cB8I9R4dLq0btGyDELSkeSA',
    appId: dotenv.env['FIREBASE_IOS_APP_ID'] ?? '1:712998131650:ios:9c918535914736acdd685b',
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '712998131650',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'govease-keshara',
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'govease-keshara.firebasestorage.app',
    iosBundleId: dotenv.env['FIREBASE_IOS_BUNDLE_ID'] ?? 'com.govease',
  );
}
