import 'package:flutter/widgets.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = <Locale>[
    Locale('en'),
    Locale('si'),
    Locale('ta'),
  ];

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appName': 'GovEase',
      'welcome': 'Welcome',
      'signIn': 'Sign In',
      'signUp': 'Sign Up',
      'home': 'Home',
      'services': 'Services',
      'complaints': 'Complaints',
      'profile': 'Profile',
      'myProfile': 'My Profile',
      'editProfile': 'Edit Profile',
      'save': 'Save',
      'cancel': 'Cancel',
      'signOut': 'Sign Out',
      'language': 'Language',
      'selectLanguage': 'Select Language',
      'english': 'English',
      'sinhala': 'Sinhala',
      'tamil': 'Tamil',
      'fullName': 'Full Name',
      'phoneNumber': 'Phone Number',
      'nicNumber': 'NIC Number',
      'enterOtp': 'Enter OTP',
      'verifyAndSignIn': 'Verify & Sign In',
      'verifyAndFinish': 'Verify & Finish',
      'sendOtp': 'Send OTP',
      'createAccount': 'Create Account',
      'pleaseFillAllFields': 'Please fill all fields',
      'invalidNic': 'Please enter a valid NIC number.',
      'invalidPhone': 'Please enter a valid Sri Lankan phone number.',
      'nicPhoneMismatch': 'NIC and phone number do not match.',
      'nicNotFound': 'NIC number not found. Please check and try again.',
      'profileUpdated': 'Profile updated successfully!',
      'profilePhotoUpdated': 'Profile photo updated successfully!',
      'failedToUploadPhoto': 'Failed to upload photo',
      'uploadingPhoto': 'Uploading photo...',
      'changeLanguage': 'Change Language',
      'languageSaved': 'Language updated successfully.',
      'updateYourInformation': 'Update your information',
      'viewAndManageAccount': 'View and manage your account',
      'accountInformation': 'Account Information',
      'memberSince': 'Member Since',
      'citizen': 'Citizen',
      'governmentOfficer': 'Government Officer',
      'support': 'Support',
      'helpCenter': 'Help Center',
      'faqsAndSupportGuides': 'FAQs and support guides',
      'sendFeedback': 'Send Feedback',
      'helpUsImprove': 'Help us improve',
      'thisNicAlreadyRegistered':
          'This NIC is already registered. Please sign in.',
      'phoneAlreadyRegistered':
          'This phone number is already linked to an existing account. Please sign in.',
      'failedToSendOtp': 'Failed to send OTP. Please try again.',
      'invalidOtp': 'Invalid OTP',
      'accountCreatedSuccessfully': 'Account created successfully!',
      'accessDenied': 'Access denied',
      'officerOnlyPortal': 'Only officers and admins can access this portal.',
      'goToHome': 'Go to Home',
      'welcomeToGovEase': 'Welcome to GovEase',
      'welcomeSubtitleLong':
          'Your digital bridge to local government services in Sri Lanka.',
      'servicesCardDescription': 'Access all government services in one place',
      'fastProcessing': 'Fast Processing',
      'fastProcessingDescription':
          'Quick and hassle-free application processing',
      'secureDescription': 'Your data is encrypted and protected',
      'activeApplications': 'Active Applications',
      'applications': 'Applications',
      'inProgress': 'In Progress',
      'completion': 'Completion',
      'applyService': 'Apply Service',
      'certificateAndApprovals': 'Certificate and approvals',
      'newComplaintTitleShort': 'New Complaint',
      'reportLocalIssue': 'Report a local issue',
      'trackStatus': 'Track Status',
      'seeAllApplications': 'See all applications',
      'updateCitizenDetails': 'Update citizen details',
      'quickActions': 'Quick Actions',
      'quickActionsSubtitle': 'Get things done in fewer taps',
      'wasteCollectionTitle': 'Waste Collection',
      'wasteCollectionSubtitle':
          'See your area\'s tractor schedule and next pickup time',
      'viewWasteSchedule': 'View Schedule',
      'weeklyCollectionSchedule': 'Weekly Schedule',
      'wasteCollectionHelpText':
          'Schedules are shown using your registered area.',
      'nextCollection': 'Next Collection',
      'wasteCollectionUpdated': 'Updated',
      'collectionDay': 'Collection Day',
      'collectionTime': 'Time',
      'collectionRoute': 'Route',
      'collectionNotes': 'Notes',
      'noWasteScheduleYet': 'No schedule is available yet.',
      'wasteScheduleMissingMessage':
          'Your local authority has not published a schedule for this area yet. Check back later.',
      'yourArea': 'Your Area',
      'refresh': 'Refresh',
      'plannedStops': 'planned stops',
      'appointmentTitle': 'GN Appointment',
      'appointmentSubtitle': 'Book a meeting with your local Grama Niladhari',
      'bookGnAppointment': 'Book GN Appointment',
      'bookGnAppointmentSubtitle':
          'Reserve a time slot for in-person or phone guidance.',
      'bookAppointmentAction': 'Book Appointment',
      'appointmentHeroSubtitle':
          'Choose a date, time slot, and reason. We will keep the request organized for your area.',
      'appointmentFormTitle': 'Appointment Details',
      'appointmentFormSubtitle':
          'Tell us what you need and when you prefer to meet',
      'appointmentSubjectLabel': 'Reason for meeting',
      'appointmentSubjectGeneral': 'General meeting',
      'appointmentSubjectDocument': 'Document verification',
      'appointmentSubjectLand': 'Land or address issue',
      'appointmentSubjectComplaint': 'Complaint follow-up',
      'appointmentSubjectCertificate': 'Certificate support',
      'appointmentReasonLabel': 'Reason',
      'appointmentReasonHint': 'Explain the issue or request in a few lines',
      'appointmentReasonTooShort': 'Please enter a more detailed reason.',
      'selectAppointmentDate': 'Select appointment date',
      'preferredDate': 'Preferred date',
      'preferredTimeSlot': 'Preferred time slot',
      'appointmentSlotMorning': 'Morning',
      'appointmentSlotAfternoon': 'Afternoon',
      'appointmentSlotEvening': 'Evening',
      'appointmentMode': 'Meeting mode',
      'appointmentModeInPerson': 'In person',
      'appointmentModePhone': 'Phone call',
      'urgentRequest': 'Mark as urgent',
      'urgentRequestSubtitle':
          'Use this only if the matter needs quicker attention',
      'additionalNotes': 'Additional notes',
      'submitAppointment': 'Submit Appointment',
      'appointmentSubmitted': 'Appointment submitted',
      'appointmentSubmittedMessage': 'Your appointment reference is',
      'appointmentSubmitFailed': 'Failed to submit appointment',
      'upcomingAppointments': 'Upcoming Appointments',
      'plannedAppointments': 'planned appointments',
      'noAppointmentsYet': 'No appointments yet',
      'appointmentEmptyStateMessage':
          'Once you book an appointment, it will appear here with status updates.',
      'cancelAppointment': 'Cancel Appointment',
      'appointmentRequiresSignIn': 'Sign in to book an appointment',
      'appointmentSignInMessage':
          'Your appointment can be tied to your verified citizen profile and area details.',
      'appointmentAreaUnknown': 'Area not loaded yet',
      'appointmentHelpText':
          'Appointments are stored with your verified profile so the officer can review the request for the correct local area.',
      'scheduledFor': 'Scheduled for',
      'officerNote': 'Officer note',
      'officerGnAppointmentsTitle': 'GN Appointments',
      'officerGnAppointmentsSubtitle':
          'Review and manage citizen appointment requests',
      'officerGnInboxTitle': 'GN Appointment Inbox',
      'officerGnInboxDescription':
          'Review requests, set new dates, and keep citizens updated.',
      'officerScopeAllAreasAdmin': 'Scope: All areas (Admin)',
      'officerScopeNoAreaAssigned': 'Scope: No area assigned',
      'officerScopePrefix': 'Scope',
      'officerStatNew': 'New',
      'officerSearchAppointmentsHint': 'Search by name, reference, or area...',
      'officerAppointmentsFound': 'appointments found',
      'officerNoAppointmentsForArea': 'No appointments found for your area.',
      'officerProfileLoadError': 'Unable to load officer profile.',
      'officerAppointmentsLoadError': 'Error loading appointments',
      'officerApproveAppointment': 'Approve Appointment',
      'officerApproveHint': 'Optional note for the citizen',
      'officerDeclineAppointment': 'Decline Appointment',
      'officerDeclineHint': 'Add a reason or next step for the citizen',
      'officerMarkCompleted': 'Mark as Completed',
      'officerCompleteHint': 'Optional completion note',
      'officerRescheduleAppointment': 'Reschedule Appointment',
      'officerRescheduleHint': 'Optional reschedule note',
      'officerSelectNewDate': 'Select new appointment date',
      'officerNewDatePrefix': 'New date',
      'officerAppointmentUpdated': 'Appointment updated successfully',
      'officerAppointmentUpdateFailed': 'Failed to update appointment',
      'officerReviewApplicationApproved': 'Application Approved',
      'officerReviewCertificateSent':
          'A secure QR-coded certificate has been generated and sent to the citizen app.',
      'officerReviewCertificate': 'Certificate',
      'officerReviewBackToApplications': 'Back to Applications',
      'officerReviewApplicationDetails': 'Application Details',
      'officerReviewCitizenDetails': 'Citizen Details',
      'officerReviewApplicantId': 'Applicant ID',
      'officerReviewUnknown': 'Unknown',
      'officerReviewSubmittedDate': 'Submitted Date',
      'officerReviewContactContext': 'Contact Context',
      'officerReviewContactContextHint':
          'View full profile for contact details',
      'officerReviewServiceRequest': 'Service Request',
      'officerReviewPayloadHint':
          'Data payload dynamically captured from submission forms. Data model varies per service type.',
      'officerReviewUploadedDocuments': 'Uploaded Documents',
      'officerReviewIdentityDocument': 'Identity Document',
      'officerReviewSupportingProof': 'Supporting Proof',
      'officerReviewOfficerRemarks': 'Officer Remarks',
      'officerReviewRemarksHint':
          'Add comments or reasons for your decision...',
      'officerReviewMissingDocs': 'Missing Docs',
      'officerReviewMissingDocsText':
          'Missing mandatory proof documents. Please re-upload.',
      'officerReviewAddressMismatch': 'Address Mismatch',
      'officerReviewAddressMismatchText':
          'The address in the document does not match your profile.',
      'officerReviewApprovedOk': 'Approved OK',
      'officerReviewApprovedOkText':
          'All details verified. Certificate generated successfully.',
      'officerAppsStatusMoved': 'Application status updated.',
      'officerAppsCertificateIssued':
          'Certificate issued and attached to application.',
      'officerAppsNoPendingInView': 'No pending applications in current view.',
      'officerAppsBulkAction': 'Bulk Action',
      'officerAppsBulkActionPrompt':
          'Apply action to filtered GN applications?',
      'officerAppsBulkReject': 'Bulk Reject',
      'officerAppsBulkComplete': 'Bulk Complete',
      'officerAppsBulkDone': 'Bulk action completed.',
      'officerAppsReview': 'Review',
      'officerAppsStartReview': 'Start Review',
      'officerAppsReject': 'Reject',
      'officerAppsNoDataExport': 'No data to export',
      'officerAppsDeskTitle': 'GN Applications Desk',
      'officerAppsDeskSubtitle':
          'GN-routed applications only (central authority hidden)',
      'officerAppsCommandCenter': 'GN Application Command Center',
      'officerAppsScopeFallback':
          'Scope mode: showing all GN-routed applications (citizen area tags incomplete)',
      'officerAppsScopeAssigned': 'Scope mode: GN + assigned area only',
      'officerAppsSearchHint': 'Search by citizen, NIC, area, service, ID',
      'officerAppsExportCsv': 'Export CSV',
      'officerAppsNoResults': 'No GN-routed applications found for this view.',
      'officerComplaintsStatusUpdated': 'Complaint status updated.',
      'officerComplaintsDeskTitle': 'Field Complaints',
      'officerComplaintsDeskSubtitle':
          'Real-time grievance monitoring and response desk',
      'officerComplaintsCommandCenter': 'Complaint Command Center',
      'officerComplaintsScopeFallback':
          'Scope mode: showing all complaints (location tags are incomplete)',
      'officerComplaintsScopeAssigned': 'Scope mode: assigned area filtering',
      'officerComplaintsFound': 'complaints found',
      'officerComplaintsNoMatch': 'No complaints match your filters.',
      'officerAppsOverdue': 'Overdue',
      'officerComplaintsEscalated': 'Escalated',
      'officerComplaintsHighPriority': 'High Priority',
      'officerComplaintsMap': 'Map',
      'officerComplaintsCall': 'Call',
      'officerComplaintsMarkInspected': 'Mark Inspected',
      'officerComplaintsEscalate': 'Escalate',
      'officerScopeDataQualityCheck': 'Data quality check',
      'officerAppsMissingAreaTags':
          'GN applications have missing citizen area tags.',
      'officerComplaintsMissingLocationTags':
          'complaints are missing location tags.',
      'officerScopeFallbackDisabledNotice':
          'Scope fallback is disabled by default; complete onboarding area mapping for reliable area routing.',
      'officerReviewNoPayloadFound':
          'No submitted payload fields found for this request.',
      'officerReviewNoDocumentsFound':
          'No uploaded documents found for this application.',
      'officerReviewInvalidDocumentUrl': 'Invalid document URL.',
      'officerReviewOpenDocumentFailed': 'Unable to open document link.',
      'walletNoCertificates': 'No certificates available in your wallet.',
      'walletRef': 'Ref',
      'walletIssued': 'Issued',
      'walletIntegrity': 'Integrity',
      'walletNotAvailable': 'Not available',
      'walletValidate': 'Validate',
      'walletVerifyQr': 'Verify QR',
      'walletDownload': 'Download',
      'walletShare': 'Share',
      'walletVerifyCertificate': 'Verify Certificate',
      'walletValidateCertificate': 'Validate Certificate',
      'walletCertificateReference': 'Certificate Reference',
      'walletCertificateVerified': 'Certificate Verified',
      'walletCertificateNotVerified': 'Certificate Not Verified',
      'walletReferenceValidFor': 'Reference is valid for',
      'walletCertificateActive': 'Issued certificate is active.',
      'walletNoActiveCertificate':
          'No active certificate found for the given reference.',
      'statusRequested': 'Requested',
      'statusApproved': 'Approved',
      'statusRescheduled': 'Rescheduled',
      'statusDeclined': 'Declined',
      'actionApprove': 'Approve',
      'actionReschedule': 'Reschedule',
      'actionDecline': 'Decline',
      'actionMarkCompleted': 'Mark Completed',
      'change': 'Change',
      'seeAll': 'See All',
      'noActiveApplicationsYet': 'No active applications yet',
      'startFirstRequest':
          'Start your first request to track approvals and progress here.',
      'applyNow': 'Apply Now',
      'secureDocs': 'Secure Docs',
      'fastUpdates': 'Fast Updates',
      'verifiedService': 'Verified Service',
      'myApplicationsTitle': 'My Applications',
      'myApplicationsSubtitle': 'Track status and progress in real time',
      'everythingInOnePlace': 'Everything in one place',
      'monitorSubmissionsProgress':
          'Monitor submissions, progress, and completion updates instantly.',
      'noApplicationsFound': 'No applications found',
      'viewDetails': 'View Details',
      'all': 'All',
      'completed': 'Completed',
      'rejected': 'Rejected',
      'pendingAction': 'Pending Action',
      'submitted': 'Submitted',
      'verified': 'Verified',
      'processing': 'Processing',
      'finalizing': 'Finalizing',
      'done': 'Done',
      'appliedOn': 'Applied on',
      'complaintsSubtitle': 'Track issues and responses in real time',
      'pastComplaints': 'Past Complaints',
      'raiseIssuesCleanly': 'Raise issues cleanly',
      'complaintsHeroSubtitle':
          'Submit complaints, monitor updates, and follow resolution progress.',
      'lodgeNewComplaint': 'Lodge New Complaint',
      'noComplaintsFound': 'No complaints found',
      'lastUpdatedOn': 'Last updated on',
      'category': 'Category',
      'status': 'Status',
      'updated': 'Updated',
      'close': 'Close',
      'open': 'Open',
      'inspected': 'Inspected',
      'closed': 'Closed',
      'submittedSuccessTitle': 'Submitted!',
      'complaintSubmittedMessage':
          'Your complaint has been logged successfully. Reference ID:',
      'backToHome': 'Back to Home',
      'newComplaintTitle': 'New Complaint',
      'newComplaintSubtitle': 'Share issue details and submit in a few steps',
      'issueCategory': 'Issue Category',
      'complaintTitle': 'Complaint Title',
      'detailedDescription': 'Detailed Description',
      'location': 'Location',
      'reviewDetails': 'Review Details',
      'notSelected': 'Not selected',
      'title': 'Title',
      'submitAccuracyNotice':
          'By submitting, you agree that the information provided is accurate.',
      'previous': 'Previous',
      'submitComplaint': 'Submit Complaint',
      'continue': 'Continue',
      'error': 'Error',
      'saving': 'Saving...',
      'errorUpdatingProfile': 'Error updating profile',
      'failedToUpdateLanguage': 'Failed to update language',
      'userName': 'User Name',
      'nicId': 'NIC / ID',
      'enterYourFullName': 'Enter your full name',
      'enterYourPhoneNumber': 'Enter your phone number',
      'nicCannotBeChanged': 'NIC cannot be changed',
      'loadingUserInformation': 'Loading user information...',
      'role': 'Role',
      'division': 'Division',
      'administrativeArea': 'Administrative Area',
      'province': 'Province',
      'district': 'District',
      'pradeshiyaSabha': 'Pradeshiya Sabha',
      'gramasewaWasama': 'Gramasewa Wasama',
      'selectProvince': 'Select province',
      'selectDistrict': 'Select district',
      'selectPradeshiyaSabha': 'Select Pradeshiya Sabha',
      'selectGramasewaWasama': 'Select Gramasewa Wasama',
      'enterPradeshiyaSabha': 'Enter Pradeshiya Sabha name',
      'enterGramasewaWasama': 'Enter Gramasewa Wasama name',
      'pleaseSelectAdministrativeArea':
          'Please select Province, District, Pradeshiya Sabha and Gramasewa Wasama.',
      'loadingAdministrativeAreas': 'Loading administrative areas...',
      'complaintTitleHint': 'e.g. Broken water pipe near main road',
      'describeIssueInDetail': 'Describe the issue in detail...',
      'locationHint': 'Enter street name or landmark',
      'sortBy': 'Sort by',
      'newestFirst': 'Newest First',
      'oldestFirst': 'Oldest First',
      'sortStatus': 'Status',
      'highestPriority': 'Highest Priority',
      'anyPriority': 'Any Priority',
      'priorityFirst': 'Priority First',
      'safetyRiskFirst': 'Safety Risk First',
      'officerComplaintsSearchHint': 'Search by title, area, category, ID',
      'priority': 'Priority',
      'landmark': 'Landmark',
      'incidentDateTime': 'Incident Date/Time',
      'safetyRisk': 'Safety Risk',
      'anonymous': 'Anonymous',
      'followUpAllowed': 'Follow-up Allowed',
      'preferredContact': 'Preferred Contact',
      'phone': 'Phone',
      'email': 'Email',
      'affectedPeople': 'Affected People',
      'description': 'Description',
      'additionalDetails': 'Additional Details',
      'yes': 'Yes',
      'no': 'No',
      'low': 'Low',
      'medium': 'Medium',
      'high': 'High',
      'critical': 'Critical',
      'pleaseSelectService': 'Please select a service to continue',
      'serviceNotFound': 'Service not found',
      'pleaseFillIn': 'Please fill in',
      'pleaseUpload': 'Please upload',
      'serviceApplicationTitle': 'Service Application',
      'serviceApplicationSubtitle':
          'Submit details and finish payment in one flow',
      'step': 'Step',
      'of': 'of',
      'selectGovernmentService': 'Select Government Service',
      'serviceSelectionSubtitle':
          'Each service has specific requirements and processing timelines',
      'serviceTypeNotFound': 'Service type not found',
      'serviceDetails': 'Service Details',
      'requiredDocuments': 'Required Documents',
      'uploadRequiredDocumentsNote':
          'Please upload digital copies of the following:',
      'upload': 'Upload',
      'uploadFailed': 'Upload failed',
      'uploaded': 'Uploaded ✓',
      'uploading': 'uploading...',
      'changeFile': 'Change File',
      'browseFiles': 'Browse Files',
      'reviewAndConfirm': 'Review & Confirm',
      'service': 'Service',
      'submittedInformation': 'Submitted Information',
      'applicationSubmittedAfterPayment':
          'Your application will be submitted only after successful payment',
      'proceedToPayment': 'Proceed to Payment',
      'paymentCancelled': 'Payment cancelled',
      'paymentError': 'Payment Error',
      'paymentSuccessful': 'Payment Successful!',
      'paymentSuccessMessagePrefix':
          'Your payment for has been processed and your application was submitted successfully.',
      'transactionId': 'Transaction ID',
      'checkout': 'Checkout',
      'securePaymentViaPayHere': 'Secure payment via PayHere',
      'paymentSetupMissing': 'Payment setup missing',
      'serverError': 'Server Error',
      'signInToGovEase': 'Sign In to GovEase',
      'chooseAccessTypeSubtitle':
          'Choose your access type and continue securely',
      'officer': 'Officer',
      'dontHaveAccount': "Don't have an account? ",
      'nicExampleLong': 'e.g. 199512345678',
      'nicFormatHint': 'Use NIC format: 12 digits or 9 digits + V/X',
      'phoneExample': 'e.g. 077 123 4567',
      'phoneFormatHint': 'Use 10-digit local number (e.g. 07XXXXXXXX)',
      'codeSentTo': 'Code sent to',
      'otpPlaceholder': '------',
      'changeNumber': 'Change number',
      'officerId': 'Officer ID',
      'officerIdExample': 'e.g. GN-2024-0147',
      'verificationMethod': 'Verification Method',
      'password': 'Password',
      'otp': 'OTP',
      'enterPassword': 'Enter password',
      'tapSignInSendOfficerOtp':
          'Tap Sign In to send OTP to your registered officer mobile number.',
      'otpDigitsPlaceholder': '000000',
      'sendOtpAndContinue': 'Send OTP & Continue',
      'signInAsOfficer': 'Sign In as Officer',
      'authorizedOfficersNotice':
          'Authorized government officers only. All actions are logged.',
      'verificationFailedMessage':
          'Verification failed. Please ensure the code is correct and your number is valid.',
      'otpResentSuccess': 'OTP resent successfully! Check your phone.',
      'failedToResendOtp': 'Failed to resend OTP. Please try again.',
      'verificationFailed': 'Verification failed',
      'signInFailed': 'Sign in failed',
      'verifyIdentity': 'Verify Identity',
      'signupSubtitle':
          'Join the GovEase community for seamless government services',
      'otpEntrySubtitle': 'Enter the 6-digit code sent to your mobile phone',
      'verify': 'Verify',
      'alreadyHaveAccount': 'Already have an account? ',
      'nameExample': 'e.g. John Doe',
      'resendAvailableIn': 'Resend available in',
      'sending': 'Sending...',
      'didntReceiveCodeResend': "Didn't receive code? Resend",
      'info': 'Info',
    },
    'si': {
      'appName': 'GovEase',
      'welcome': 'සාදරයෙන් පිළිගනිමු',
      'signIn': 'පිවිසෙන්න',
      'signUp': 'ලියාපදිංචි වන්න',
      'home': 'මුල් පිටුව',
      'services': 'සේවා',
      'complaints': 'පැමිණිලි',
      'profile': 'පැතිකඩ',
      'myProfile': 'මගේ පැතිකඩ',
      'editProfile': 'පැතිකඩ සංස්කරණය',
      'save': 'සුරකින්න',
      'cancel': 'අවලංගු',
      'signOut': 'ඉවත් වන්න',
      'language': 'භාෂාව',
      'selectLanguage': 'භාෂාව තෝරන්න',
      'english': 'ඉංග්රීසි',
      'sinhala': 'සිංහල',
      'tamil': 'දෙමළ',
      'fullName': 'සම්පූර්ණ නම',
      'phoneNumber': 'දුරකථන අංකය',
      'nicNumber': 'ජා.හැ.අංකය',
      'enterOtp': 'OTP ඇතුළත් කරන්න',
      'verifyAndSignIn': 'තහවුරු කර පිවිසෙන්න',
      'verifyAndFinish': 'තහවුරු කර අවසන් කරන්න',
      'sendOtp': 'OTP යවන්න',
      'createAccount': 'ගිණුම සාදන්න',
      'pleaseFillAllFields': 'කරුණාකර සියලුම ක්ෂේත්‍ර පුරවන්න',
      'invalidNic': 'කරුණාකර වලංගු NIC අංකයක් ඇතුළත් කරන්න.',
      'invalidPhone': 'කරුණාකර වලංගු ශ්‍රී ලංකා දුරකථන අංකයක් ඇතුළත් කරන්න.',
      'nicPhoneMismatch': 'NIC සහ දුරකථන අංකය නොගැලපේ.',
      'nicNotFound': 'NIC අංකය හමු නොවීය. නැවත පරීක්ෂා කරන්න.',
      'profileUpdated': 'පැතිකඩ සාර්ථකව යාවත්කාලීන විය!',
      'profilePhotoUpdated': 'පැතිකඩ ඡායාරූපය සාර්ථකව යාවත්කාලීන විය!',
      'failedToUploadPhoto': 'ඡායාරූපය උඩුගත කිරීම අසාර්ථකයි',
      'uploadingPhoto': 'ඡායාරූපය උඩුගත වෙමින්...',
      'changeLanguage': 'භාෂාව වෙනස් කරන්න',
      'languageSaved': 'භාෂාව සාර්ථකව යාවත්කාලීන විය.',
      'updateYourInformation': 'ඔබගේ තොරතුරු යාවත්කාලීන කරන්න',
      'viewAndManageAccount': 'ඔබගේ ගිණුම බලන්න සහ කළමනාකරණය කරන්න',
      'accountInformation': 'ගිණුම් තොරතුරු',
      'memberSince': 'සාමාජික since',
      'citizen': 'පුරවැසියා',
      'governmentOfficer': 'රාජ්‍ය නිලධාරී',
      'support': 'සහාය',
      'helpCenter': 'උදව් මධ්‍යස්ථානය',
      'faqsAndSupportGuides': 'ප්‍රශ්න හා සහාය මාර්ගෝපදේශ',
      'sendFeedback': 'ප්‍රතිචාර යවන්න',
      'helpUsImprove': 'අපිට වැඩිදියුණු වීමට උදව් කරන්න',
      'thisNicAlreadyRegistered':
          'මෙම NIC එක දැනටමත් ලියාපදිංචි කර ඇත. කරුණාකර පිවිසෙන්න.',
      'phoneAlreadyRegistered':
          'මෙම දුරකථන අංකය දැනටමත් පවතින ගිණුමකට සම්බන්ධ කර ඇත. කරුණාකර පිවිසෙන්න.',
      'failedToSendOtp': 'OTP යැවීමට අසාර්ථක විය. නැවත උත්සාහ කරන්න.',
      'invalidOtp': 'අවලංගු OTP',
      'accountCreatedSuccessfully': 'ගිණුම සාර්ථකව සාදන ලදි!',
      'accessDenied': 'ප්‍රවේශය අවහිරයි',
      'officerOnlyPortal':
          'මෙම ද්වාරයට ප්‍රවේශ විය හැක්කේ නිලධාරීන් සහ පරිපාලකයින්ට පමණි.',
      'goToHome': 'මුල් පිටුවට යන්න',
      'welcomeToGovEase': 'GovEase වෙත සාදරයෙන් පිළිගනිමු',
      'welcomeSubtitleLong':
          'ශ්‍රී ලංකාවේ පළාත් පාලන සේවාවන් සඳහා ඔබගේ ඩිජිටල් පාලම.',
      'servicesCardDescription': 'සියලුම රජයේ සේවා එක් තැනකින් ප්‍රවේශ වන්න',
      'fastProcessing': 'වේගවත් සැකසීම',
      'fastProcessingDescription': 'ඉක්මන් සහ පහසු අයදුම්පත් සැකසීම',
      'secureDescription': 'ඔබගේ දත්ත සංකේතනය කර ආරක්ෂා කර ඇත',
      'activeApplications': 'සක්‍රීය අයදුම්පත්',
      'applications': 'අයදුම්පත්',
      'inProgress': 'ක්‍රියාත්මක වෙමින්',
      'completion': 'සම්පූර්ණය',
      'applyService': 'සේවාවට අයදුම් කරන්න',
      'certificateAndApprovals': 'සහතික සහ අනුමැතියන්',
      'newComplaintTitleShort': 'නව පැමිණිල්ලක්',
      'reportLocalIssue': 'ප්‍රාදේශීය ගැටලුවක් වාර්තා කරන්න',
      'trackStatus': 'තත්ත්වය බලන්න',
      'seeAllApplications': 'සියලු අයදුම්පත් බලන්න',
      'updateCitizenDetails': 'පුරවැසි තොරතුරු යාවත්කාලීන කරන්න',
      'quickActions': 'ක්ෂණික ක්‍රියා',
      'quickActionsSubtitle': 'අඩු touches වලින් වැඩ ඉවර කරන්න',
      'wasteCollectionTitle': 'කුණු එකතු කිරීම',
      'wasteCollectionSubtitle':
          'ඔබගේ ප්‍රදේශයේ ට්‍රැක්ටර් කාලසටහන සහ ඊළඟ එකතු කිරීමේ වේලාව බලන්න',
      'viewWasteSchedule': 'කාලසටහන බලන්න',
      'weeklyCollectionSchedule': 'සතිපතා කාලසටහන',
      'wasteCollectionHelpText':
          'කාලසටහන් ඔබගේ ලියාපදිංචි ප්‍රදේශය අනුව පෙන්වයි.',
      'nextCollection': 'ඊළඟ එකතු කිරීම',
      'wasteCollectionUpdated': 'යාවත්කාලීන විය',
      'collectionDay': 'එකතු කරන දිනය',
      'collectionTime': 'වේලාව',
      'collectionRoute': 'මාර්ගය',
      'collectionNotes': 'සටහන්',
      'noWasteScheduleYet': 'තවම කාලසටහනක් නොමැත.',
      'wasteScheduleMissingMessage':
          'ඔබගේ පළාත් පාලන ආයතනය තවම මෙම ප්‍රදේශය සඳහා කාලසටහනක් ප්‍රකාශයට පත් කර නොමැත. පසුව නැවත පරීක්ෂා කරන්න.',
      'yourArea': 'ඔබගේ ප්‍රදේශය',
      'refresh': 'යාවත්කාලීන කරන්න',
      'plannedStops': 'සැලසුම් කළ නැවතුම්',
      'appointmentTitle': 'GN හමුවීම',
      'appointmentSubtitle':
          'ඔබගේ ප්‍රාදේශීය ග්‍රාම නිලධාරියා හමුවීමට වේලාවක් වෙන් කරන්න',
      'bookGnAppointment': 'GN හමුවීම වෙන් කරන්න',
      'bookGnAppointmentSubtitle':
          'සිතූ පරිදි හමුවීමට හෝ දුරකථන මඟින් උපදෙස් ලබා ගැනීමට වේලාවක් වෙන් කරන්න.',
      'bookAppointmentAction': 'හමුවීම වෙන් කරන්න',
      'appointmentHeroSubtitle':
          'දිනය, වේලාව සහ හේතුව තෝරන්න. ඔබගේ ප්‍රදේශයට ගැළපෙන ලෙස ඉල්ලීම සුරකිමු.',
      'appointmentFormTitle': 'හමුවීමේ විස්තර',
      'appointmentFormSubtitle':
          'ඔබට අවශ්‍ය දේ සහ හමුවීමට කැමති වේලාව සඳහන් කරන්න',
      'appointmentSubjectLabel': 'හමුවීමේ හේතුව',
      'appointmentSubjectGeneral': 'සාමාන්‍ය හමුවීම',
      'appointmentSubjectDocument': 'ලේඛන තහවුරු කිරීම',
      'appointmentSubjectLand': 'ඉඩම් හෝ ලිපින ගැටලුව',
      'appointmentSubjectComplaint': 'පැමිණිල්ල අනුගමනය',
      'appointmentSubjectCertificate': 'සහතික සහාය',
      'appointmentReasonLabel': 'හේතුව',
      'appointmentReasonHint': 'ගැටලුව හෝ ඉල්ලීම වචන කිහිපයකින් විස්තර කරන්න',
      'appointmentReasonTooShort':
          'කරුණාකර වැඩි විස්තර සහිත හේතුවක් ඇතුළත් කරන්න.',
      'selectAppointmentDate': 'හමුවීමේ දිනය තෝරන්න',
      'preferredDate': 'කැමති දිනය',
      'preferredTimeSlot': 'කැමති වේලාව',
      'appointmentSlotMorning': 'උදෑසන',
      'appointmentSlotAfternoon': 'දහවල්',
      'appointmentSlotEvening': 'සවස',
      'appointmentMode': 'හමුවීමේ ක්‍රමය',
      'appointmentModeInPerson': 'සෘජු හමුවීම',
      'appointmentModePhone': 'දුරකථන ඇමතුම',
      'urgentRequest': 'හදිසි ලෙස සලකන්න',
      'urgentRequestSubtitle':
          'මේක භාවිතා කරන්න නම් කාරණාව ඉක්මන් අවධානයක් අවශ්‍ය විට',
      'additionalNotes': 'අමතර සටහන්',
      'submitAppointment': 'හමුවීම යවන්න',
      'appointmentSubmitted': 'හමුවීම යවන ලදී',
      'appointmentSubmittedMessage': 'ඔබගේ හමුවීමේ යොමු අංකය',
      'appointmentSubmitFailed': 'හමුවීම යැවීම අසාර්ථක විය',
      'upcomingAppointments': 'ඉදිරියේ හමුවීම්',
      'plannedAppointments': 'සැලසුම් කළ හමුවීම්',
      'noAppointmentsYet': 'තවම හමුවීම් නොමැත',
      'appointmentEmptyStateMessage':
          'ඔබ හමුවීමක් වෙන් කළ පසු එය තත්ත්ව යාවත්කාලීන සමඟ මෙහි පෙන්වනු ලැබේ.',
      'cancelAppointment': 'හමුවීම අවලංගු කරන්න',
      'appointmentRequiresSignIn': 'හමුවීමක් වෙන් කිරීමට පිවිසෙන්න',
      'appointmentSignInMessage':
          'ඔබගේ හමුවීම තහවුරු කළ පුරවැසි පැතිකඩට සහ ප්‍රදේශ විස්තරවලට සම්බන්ධ කරනු ඇත.',
      'appointmentAreaUnknown': 'ප්‍රදේශය තවම පූරණය වී නැත',
      'appointmentHelpText':
          'ඔබගේ තහවුරු කළ පැතිකඩ සමඟ හමුවීම් සුරකින බැවින් නිලධාරියාට නිවැරදි ප්‍රාදේශීය ප්‍රදේශය සඳහා ඉල්ලීම පරීක්ෂා කළ හැක.',
      'scheduledFor': 'නියමිත දිනය',
      'officerNote': 'නිලධාරි සටහන',
      'officerGnAppointmentsTitle': 'GN හමුවීම්',
      'officerGnAppointmentsSubtitle':
          'පුරවැසි හමුවීම් ඉල්ලීම් සමාලෝචනය කර කළමනාකරණය කරන්න',
      'officerGnInboxTitle': 'GN හමුවීම් ඉන්බොක්ස්',
      'officerGnInboxDescription':
          'ඉල්ලීම් සමාලෝචනය කර නව දින සකසා පුරවැසියන්ට යාවත්කාලීන දැනුම් දෙන්න.',
      'officerScopeAllAreasAdmin': 'පරාසය: සියලු ප්‍රදේශ (පරිපාලක)',
      'officerScopeNoAreaAssigned': 'පරාසය: ප්‍රදේශයක් පවරා නැත',
      'officerScopePrefix': 'පරාසය',
      'officerStatNew': 'නව',
      'officerSearchAppointmentsHint':
          'නම, යොමු අංකය හෝ ප්‍රදේශය අනුව සොයන්න...',
      'officerAppointmentsFound': 'හමුවීම් හමු විය',
      'officerNoAppointmentsForArea': 'ඔබගේ ප්‍රදේශයට හමුවීම් හමු නොවීය.',
      'officerProfileLoadError': 'නිලධාරි පැතිකඩ පූරණය කළ නොහැක.',
      'officerAppointmentsLoadError': 'හමුවීම් පූරණය කිරීමේ දෝෂයකි',
      'officerApproveAppointment': 'හමුවීම අනුමත කරන්න',
      'officerApproveHint': 'පුරවැසියා සඳහා විකල්ප සටහනක්',
      'officerDeclineAppointment': 'හමුවීම ප්‍රතික්ෂේප කරන්න',
      'officerDeclineHint': 'හේතුවක් හෝ මීළඟ පියවරක් එකතු කරන්න',
      'officerMarkCompleted': 'සම්පූර්ණ ලෙස සලකුණු කරන්න',
      'officerCompleteHint': 'විකල්ප සම්පූර්ණ කිරීමේ සටහන',
      'officerAppsReview': 'සමාලෝචනය',
      'officerAppsStartReview': 'සමාලෝචනය අරඹන්න',
      'officerAppsReject': 'ප්‍රතික්ෂේප කරන්න',
      'officerRescheduleAppointment': 'හමුවීම නැවත දිනගත කරන්න',
      'officerRescheduleHint': 'විකල්ප නැවත දිනගත කිරීමේ සටහන',
      'officerSelectNewDate': 'නව හමුවීම් දිනය තෝරන්න',
      'officerNewDatePrefix': 'නව දිනය',
      'officerAppointmentUpdated': 'හමුවීම සාර්ථකව යාවත්කාලීන විය',
      'officerAppointmentUpdateFailed': 'හමුවීම යාවත්කාලීන කිරීම අසාර්ථකයි',
      'statusRequested': 'ඉල්ලා ඇත',
      'statusApproved': 'අනුමතයි',
      'statusRescheduled': 'නැවත දිනගතයි',
      'statusDeclined': 'ප්‍රතික්ෂේපයි',
      'actionApprove': 'අනුමත කරන්න',
      'actionReschedule': 'නැවත දිනගත කරන්න',
      'actionDecline': 'ප්‍රතික්ෂේප කරන්න',
      'actionMarkCompleted': 'සම්පූර්ණයි ලෙස සලකුණු කරන්න',
      'change': 'වෙනස් කරන්න',
      'seeAll': 'සියල්ල බලන්න',
      'noActiveApplicationsYet': 'තවම සක්‍රීය අයදුම්පත් නොමැත',
      'startFirstRequest':
          'අනුමැතියන් සහ ප්‍රගතිය නිරීක්ෂණයට ඔබගේ පළමු අයදුම ආරම්භ කරන්න.',
      'applyNow': 'දැන් අයදුම් කරන්න',
      'secureDocs': 'ආරක්ෂිත ලේඛන',
      'fastUpdates': 'වේගවත් යාවත්කාලීන',
      'verifiedService': 'තහවුරු කළ සේවාව',
      'myApplicationsTitle': 'මගේ අයදුම්පත්',
      'myApplicationsSubtitle': 'තත්ත්වය සහ ප්‍රගතිය සජීවීව නිරීක්ෂණය කරන්න',
      'everythingInOnePlace': 'සියල්ලම එක් තැනක',
      'monitorSubmissionsProgress':
          'යැවීම්, ප්‍රගතිය සහ සම්පූර්ණ යාවත්කාලීන වහා නිරීක්ෂණය කරන්න.',
      'noApplicationsFound': 'අයදුම්පත් හමු නොවීය',
      'viewDetails': 'විස්තර බලන්න',
      'all': 'සියල්ල',
      'completed': 'සම්පූර්ණයි',
      'rejected': 'ප්‍රතික්ෂේපිතයි',
      'pendingAction': 'අපේක්ෂිත ක්‍රියාව',
      'submitted': 'යවන ලදී',
      'verified': 'තහවුරු කළා',
      'processing': 'සැකසෙමින්',
      'finalizing': 'අවසන් කරමින්',
      'done': 'අවසන්',
      'appliedOn': 'අයදුම් කළේ',
      'complaintsSubtitle': 'ගැටලු සහ ප්‍රතිචාර සජීවීව නිරීක්ෂණය කරන්න',
      'pastComplaints': 'පෙර පැමිණිලි',
      'raiseIssuesCleanly': 'ගැටලු පැහැදිලිව ඉදිරිපත් කරන්න',
      'complaintsHeroSubtitle':
          'පැමිණිලි යවන්න, යාවත්කාලීන නිරීක්ෂණය කරන්න, විසඳුම් ප්‍රගතිය අනුගමනය කරන්න.',
      'lodgeNewComplaint': 'නව පැමිණිල්ලක් යොමු කරන්න',
      'noComplaintsFound': 'පැමිණිලි හමු නොවීය',
      'lastUpdatedOn': 'අවසන් යාවත්කාලීන වූයේ',
      'category': 'කාණ්ඩය',
      'status': 'තත්ත්වය',
      'updated': 'යාවත්කාලීන',
      'close': 'වසන්න',
      'open': 'විවෘත',
      'inspected': 'පරීක්ෂා කළ',
      'closed': 'වසන ලදී',
      'submittedSuccessTitle': 'යවන ලදී!',
      'complaintSubmittedMessage':
          'ඔබගේ පැමිණිල්ල සාර්ථකව සටහන් විය. සොයාගැනීමේ අංකය:',
      'backToHome': 'මුල් පිටුවට ආපසු',
      'newComplaintTitle': 'නව පැමිණිල්ලක්',
      'newComplaintSubtitle': 'ගැටලු විස්තර ලබාදී පියවර කිහිපයකින් යවන්න',
      'issueCategory': 'ගැටලුවේ කාණ්ඩය',
      'complaintTitle': 'පැමිණිල්ලේ මාතෘකාව',
      'detailedDescription': 'විස්තරාත්මක විස්තරය',
      'location': 'ස්ථානය',
      'reviewDetails': 'විස්තර පරීක්ෂා කරන්න',
      'notSelected': 'තෝරා නොමැත',
      'title': 'මාතෘකාව',
      'submitAccuracyNotice':
          'යැවීම මඟින්, ලබාදුන් තොරතුරු නිවැරදි බවට ඔබ එකඟ වේ.',
      'previous': 'පෙර',
      'submitComplaint': 'පැමිණිල්ල යවන්න',
      'continue': 'ඉදිරියට',
      'error': 'දෝෂයකි',
      'saving': 'සුරකිමින්...',
      'errorUpdatingProfile': 'පැතිකඩ යාවත්කාලීන කිරීමේ දෝෂයකි',
      'failedToUpdateLanguage': 'භාෂාව යාවත්කාලීන කිරීම අසාර්ථකයි',
      'userName': 'පරිශීලක නාමය',
      'nicId': 'NIC / ID',
      'enterYourFullName': 'ඔබගේ සම්පූර්ණ නම ඇතුළත් කරන්න',
      'enterYourPhoneNumber': 'ඔබගේ දුරකථන අංකය ඇතුළත් කරන්න',
      'nicCannotBeChanged': 'NIC වෙනස් කළ නොහැක',
      'loadingUserInformation': 'පරිශීලක තොරතුරු පූරණය වෙමින්...',
      'role': 'භූමිකාව',
      'division': 'කොට්ඨාශය',
      'administrativeArea': 'පරිපාලන ප්‍රදේශය',
      'province': 'පළාත',
      'district': 'දිස්ත්‍රික්කය',
      'pradeshiyaSabha': 'ප්‍රාදේශීය සභාව',
      'gramasewaWasama': 'ග්‍රාමසේවා වසම',
      'selectProvince': 'පළාත තෝරන්න',
      'selectDistrict': 'දිස්ත්‍රික්කය තෝරන්න',
      'selectPradeshiyaSabha': 'ප්‍රාදේශීය සභාව තෝරන්න',
      'selectGramasewaWasama': 'ග්‍රාමසේවා වසම තෝරන්න',
      'enterPradeshiyaSabha': 'ප්‍රාදේශීය සභාවේ නම ඇතුළත් කරන්න',
      'enterGramasewaWasama': 'ග්‍රාමසේවා වසමේ නම ඇතුළත් කරන්න',
      'pleaseSelectAdministrativeArea':
          'කරුණාකර පළාත, දිස්ත්‍රික්කය, ප්‍රාදේශීය සභාව සහ ග්‍රාමසේවා වසම තෝරන්න.',
      'loadingAdministrativeAreas': 'පරිපාලන ප්‍රදේශ පූරණය වෙමින්...',
      'complaintTitleHint': 'උදා: ප්‍රධාන මාර්ගය අසල බිඳුණු ජල පයිප්පයක්',
      'describeIssueInDetail': 'ගැටලුව විස්තරාත්මකව සඳහන් කරන්න...',
      'locationHint': 'වීදි නාමය හෝ සලකුණ ඇතුළත් කරන්න',
      'sortBy': 'වර්ග කරන්න',
      'newestFirst': 'අලුත්ම පළමුව',
      'oldestFirst': 'පැරණිතම පළමුව',
      'sortStatus': 'තත්ත්වය',
      'highestPriority': 'ඉහළම ප්‍රමුඛතාව',
      'anyPriority': 'ඕනෑම ප්‍රමුඛතාව',
      'priorityFirst': 'ප්‍රමුඛතාව පළමුව',
      'safetyRiskFirst': 'ආරක්ෂා අවදානම් පළමුව',
      'officerComplaintsSearchHint':
          'මාතෘකාව, ප්‍රදේශය, කාණ්ඩය හෝ හැඳුනුම් අංකය අනුව සොයන්න',
      'officerScopeDataQualityCheck': 'දත්ත තත්ත්ව පරීක්ෂාව',
      'officerAppsMissingAreaTags':
          'GN අයදුම්පත් කිහිපයක පුරවැසි ප්‍රදේශ ටැග් නොපවතී.',
      'officerComplaintsMissingLocationTags':
          'පැමිණිලි කිහිපයක ස්ථාන ටැග් නොපවතී.',
      'officerScopeFallbackDisabledNotice':
          'පරාස fallback පෙරනිමියෙන් අක්‍රියයි; විශ්වාසදායක ප්‍රදේශ මාර්ගගත කිරීම සඳහා onboarding ප්‍රදේශ මැප් කිරීම සම්පූර්ණ කරන්න.',
      'officerReviewNoPayloadFound':
          'මෙම ඉල්ලීම සඳහා යවන ලද payload ක්ෂේත්‍ර හමු නොවීය.',
      'officerReviewNoDocumentsFound': 'මෙම අයදුම සඳහා උඩුගත ලේඛන හමු නොවීය.',
      'officerReviewInvalidDocumentUrl': 'වලංගු නොවන ලේඛන URL එකකි.',
      'officerReviewOpenDocumentFailed': 'ලේඛන සබැඳිය විවෘත කළ නොහැකි විය.',
      'priority': 'ප්‍රමුඛතාව',
      'landmark': 'සලකුණ',
      'incidentDateTime': 'සිදුවීමේ දිනය/වේලාව',
      'safetyRisk': 'ආරක්ෂාවට අවදානම',
      'anonymous': 'නාම රහිත',
      'followUpAllowed': 'පසු විමසීම අවසර ඇත',
      'preferredContact': 'කැමති සම්බන්ධ ක්‍රමය',
      'phone': 'දුරකථනය',
      'email': 'ඊමේල්',
      'affectedPeople': 'බලපෑමට ලක් වූ පිරිස',
      'description': 'විස්තරය',
      'additionalDetails': 'අතිරේක විස්තර',
      'yes': 'ඔව්',
      'no': 'නැහැ',
      'low': 'අඩු',
      'medium': 'මධ්‍යම',
      'high': 'ඉහළ',
      'critical': 'අති අවදානම්',
      'pleaseSelectService': 'ඉදිරියට යාමට කරුණාකර සේවාවක් තෝරන්න',
      'serviceNotFound': 'සේවාව හමු නොවීය',
      'pleaseFillIn': 'කරුණාකර පුරවන්න',
      'pleaseUpload': 'කරුණාකර උඩුගත කරන්න',
      'serviceApplicationTitle': 'සේවා අයදුම්පත',
      'serviceApplicationSubtitle':
          'විස්තර ලබාදී එකම ප්‍රවාහයකින් ගෙවීම අවසන් කරන්න',
      'step': 'පියවර',
      'of': 'යින්',
      'selectGovernmentService': 'රජයේ සේවාව තෝරන්න',
      'serviceSelectionSubtitle':
          'සෑම සේවාවකටම විශේෂ අවශ්‍යතා සහ සැකසුම් කාලසටහන් ඇත',
      'serviceTypeNotFound': 'සේවා වර්ගය හමු නොවීය',
      'serviceDetails': 'සේවා විස්තර',
      'requiredDocuments': 'අවශ්‍ය ලේඛන',
      'uploadRequiredDocumentsNote':
          'කරුණාකර පහත ලේඛනවල ඩිජිටල් පිටපත් උඩුගත කරන්න:',
      'upload': 'උඩුගත කරන්න',
      'uploadFailed': 'උඩුගත කිරීම අසාර්ථකයි',
      'uploaded': 'උඩුගත කර ඇත ✓',
      'uploading': 'උඩුගත වෙමින්...',
      'changeFile': 'ගොනුව වෙනස් කරන්න',
      'browseFiles': 'ගොනු සොයන්න',
      'reviewAndConfirm': 'සමාලෝචනය කර තහවුරු කරන්න',
      'service': 'සේවාව',
      'submittedInformation': 'යවන ලද තොරතුරු',
      'applicationSubmittedAfterPayment':
          'ඔබගේ අයදුම යවන්නේ සාර්ථක ගෙවීමෙන් පසුව පමණි',
      'proceedToPayment': 'ගෙවීමට ඉදිරියට යන්න',
      'paymentCancelled': 'ගෙවීම අවලංගු කළා',
      'paymentError': 'ගෙවීම් දෝෂය',
      'paymentSuccessful': 'ගෙවීම සාර්ථකයි!',
      'paymentSuccessMessagePrefix':
          'ඔබගේ ගෙවීම සාර්ථකව සැකසී ඇත, අයදුමද සාර්ථකව යවා ඇත.',
      'transactionId': 'ගනුදෙනු අංකය',
      'checkout': 'ගෙවීම් අවසන් කිරීම',
      'securePaymentViaPayHere': 'PayHere හරහා ආරක්ෂිත ගෙවීම',
      'paymentSetupMissing': 'ගෙවීම් සැකසුම අඩුයි',
      'serverError': 'සේවාදායක දෝෂය',
      'signInToGovEase': 'GovEase වෙත පිවිසෙන්න',
      'chooseAccessTypeSubtitle':
          'ඔබගේ ප්‍රවේශ වර්ගය තෝරා ආරක්ෂිතව ඉදිරියට යන්න',
      'officer': 'නිලධාරී',
      'dontHaveAccount': 'ගිණුමක් නැද්ද? ',
      'nicExampleLong': 'උදා: 199512345678',
      'nicFormatHint': 'NIC ආකෘතිය: අංක 12ක් හෝ අංක 9ක් + V/X',
      'phoneExample': 'උදා: 077 123 4567',
      'phoneFormatHint': 'අංක 10ක දේශීය අංකයක් භාවිත කරන්න (07XXXXXXXX)',
      'codeSentTo': 'කේතය යවා ඇත',
      'otpPlaceholder': '------',
      'changeNumber': 'අංකය වෙනස් කරන්න',
      'officerId': 'නිලධාරි හැඳුනුම් අංකය',
      'officerIdExample': 'උදා: GN-2024-0147',
      'verificationMethod': 'තහවුරු කිරීමේ ක්‍රමය',
      'password': 'මුරපදය',
      'otp': 'OTP',
      'enterPassword': 'මුරපදය ඇතුළත් කරන්න',
      'tapSignInSendOfficerOtp':
          'නිලධාරි ජංගම අංකයට OTP යැවීමට Sign In තට්ටු කරන්න.',
      'otpDigitsPlaceholder': '000000',
      'sendOtpAndContinue': 'OTP යවා ඉදිරියට',
      'signInAsOfficer': 'නිලධාරියෙකු ලෙස පිවිසෙන්න',
      'authorizedOfficersNotice':
          'අනුමත රජයේ නිලධාරින්ට පමණි. සියලු ක්‍රියා ලොග් වේ.',
      'verificationFailedMessage':
          'තහවුරු කිරීම අසාර්ථකයි. කේතය නිවැරදිද සහ අංකය වලංගුද පරීක්ෂා කරන්න.',
      'otpResentSuccess': 'OTP නැවත යවා ඇත! දුරකථනය පරීක්ෂා කරන්න.',
      'failedToResendOtp': 'OTP නැවත යැවීම අසාර්ථකයි. නැවත උත්සාහ කරන්න.',
      'verificationFailed': 'තහවුරු කිරීම අසාර්ථකයි',
      'signInFailed': 'පිවිසීම අසාර්ථකයි',
      'verifyIdentity': 'අනන්‍යතාව තහවුරු කරන්න',
      'signupSubtitle': 'GovEase සමඟ සම්බන්ධ වී සේවා පහසු ලෙස ලබාගන්න',
      'otpEntrySubtitle': 'ඔබගේ ජංගමයට යවූ අංක 6ක කේතය ඇතුළත් කරන්න',
      'verify': 'තහවුරු කරන්න',
      'alreadyHaveAccount': 'දැනටමත් ගිණුමක් තිබේද? ',
      'nameExample': 'උදා: කසුන් පෙරේරා',
      'resendAvailableIn': 'නැවත යැවීම ලබාගත හැක්කේ',
      'sending': 'යවමින්...',
      'didntReceiveCodeResend': 'කේතය නොලැබුණාද? නැවත යවන්න',
      'info': 'තොරතුරු',
    },
    'ta': {
      'appName': 'GovEase',
      'welcome': 'வரவேற்கிறோம்',
      'signIn': 'உள்நுழை',
      'signUp': 'பதிவு செய்',
      'home': 'முகப்பு',
      'services': 'சேவைகள்',
      'complaints': 'புகார்கள்',
      'profile': 'சுயவிவரம்',
      'myProfile': 'என் சுயவிவரம்',
      'editProfile': 'சுயவிவரம் திருத்து',
      'save': 'சேமி',
      'cancel': 'ரத்து செய்',
      'signOut': 'வெளியேறு',
      'language': 'மொழி',
      'selectLanguage': 'மொழியை தேர்வு செய்',
      'english': 'ஆங்கிலம்',
      'sinhala': 'சிங்களம்',
      'tamil': 'தமிழ்',
      'fullName': 'முழு பெயர்',
      'phoneNumber': 'தொலைபேசி எண்',
      'nicNumber': 'தேசிய அடையாள எண்',
      'enterOtp': 'OTP ஐ உள்ளிடவும்',
      'verifyAndSignIn': 'சரிபார்த்து உள்நுழை',
      'verifyAndFinish': 'சரிபார்த்து முடி',
      'sendOtp': 'OTP அனுப்பு',
      'createAccount': 'கணக்கு உருவாக்கு',
      'pleaseFillAllFields': 'தயவு செய்து அனைத்து புலங்களையும் நிரப்பவும்',
      'invalidNic': 'சரியான NIC எண்ணை உள்ளிடவும்.',
      'invalidPhone': 'சரியான இலங்கை தொலைபேசி எண்ணை உள்ளிடவும்.',
      'nicPhoneMismatch': 'NIC மற்றும் தொலைபேசி எண் பொருந்தவில்லை.',
      'nicNotFound': 'NIC எண் கிடைக்கவில்லை. மீண்டும் சரிபார்க்கவும்.',
      'profileUpdated': 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
      'profilePhotoUpdated': 'சுயவிவரப் படம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
      'failedToUploadPhoto': 'படத்தை பதிவேற்ற முடியவில்லை',
      'uploadingPhoto': 'படம் பதிவேற்றப்படுகிறது...',
      'changeLanguage': 'மொழியை மாற்று',
      'languageSaved': 'மொழி வெற்றிகரமாக புதுப்பிக்கப்பட்டது.',
      'updateYourInformation': 'உங்கள் தகவலை புதுப்பிக்கவும்',
      'viewAndManageAccount':
          'உங்கள் கணக்கைப் பாருங்கள் மற்றும் நிர்வகிக்கவும்',
      'accountInformation': 'கணக்கு தகவல்',
      'memberSince': 'உறுப்பினர் ஆன தேதி',
      'citizen': 'குடிமகன்',
      'governmentOfficer': 'அரசு அலுவலர்',
      'support': 'ஆதரவு',
      'helpCenter': 'உதவி மையம்',
      'faqsAndSupportGuides': 'கேள்விகள் மற்றும் உதவி வழிகாட்டிகள்',
      'sendFeedback': 'கருத்து அனுப்பு',
      'helpUsImprove': 'எங்களை மேம்படுத்த உதவுங்கள்',
      'thisNicAlreadyRegistered':
          'இந்த NIC ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது. தயவு செய்து உள்நுழையவும்.',
      'phoneAlreadyRegistered':
          'இந்த தொலைபேசி எண் ஏற்கனவே உள்ள கணக்குடன் இணைக்கப்பட்டுள்ளது. தயவு செய்து உள்நுழையவும்.',
      'failedToSendOtp': 'OTP அனுப்ப முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
      'invalidOtp': 'தவறான OTP',
      'accountCreatedSuccessfully': 'கணக்கு வெற்றிகரமாக உருவாக்கப்பட்டது!',
      'accessDenied': 'அணுகல் மறுக்கப்பட்டது',
      'officerOnlyPortal':
          'இந்த தளத்தை அதிகாரிகள் மற்றும் நிர்வாகிகள் மட்டுமே அணுக முடியும்.',
      'goToHome': 'முகப்புக்கு செல்',
      'welcomeToGovEase': 'GovEase இற்கு வரவேற்கிறோம்',
      'welcomeSubtitleLong':
          'இலங்கையின் உள்ளூராட்சி சேவைகளுக்கான உங்கள் டிஜிட்டல் பாலம்.',
      'servicesCardDescription':
          'அனைத்து அரசு சேவைகளையும் ஒரே இடத்தில் அணுகுங்கள்',
      'fastProcessing': 'வேகமான செயலாக்கம்',
      'fastProcessingDescription':
          'விரைவு மற்றும் சிரமமற்ற விண்ணப்ப செயலாக்கம்',
      'secureDescription':
          'உங்கள் தரவு குறியாக்கம் செய்யப்பட்டு பாதுகாக்கப்படுகிறது',
      'activeApplications': 'செயலில் உள்ள விண்ணப்பங்கள்',
      'applications': 'விண்ணப்பங்கள்',
      'inProgress': 'நடைபெற்று வருகிறது',
      'completion': 'நிறைவு',
      'applyService': 'சேவைக்காக விண்ணப்பிக்கவும்',
      'certificateAndApprovals': 'சான்றிதழ்கள் மற்றும் அனுமதிகள்',
      'newComplaintTitleShort': 'புதிய புகார்',
      'reportLocalIssue': 'உள்ளூர் பிரச்சினையை அறிவிக்கவும்',
      'trackStatus': 'நிலையை கண்காணிக்கவும்',
      'seeAllApplications': 'அனைத்து விண்ணப்பங்களையும் காண்க',
      'updateCitizenDetails': 'குடிமகன் விவரங்களை புதுப்பிக்கவும்',
      'quickActions': 'விரைவு செயல்கள்',
      'quickActionsSubtitle': 'குறைந்த தட்டுதல்களில் வேலை முடிக்கவும்',
      'wasteCollectionTitle': 'கழிவு சேகரிப்பு',
      'wasteCollectionSubtitle':
          'உங்கள் பகுதியின் டிராக்டர் அட்டவணையும் அடுத்த சேகரிப்பு நேரமும் பார்க்கவும்',
      'viewWasteSchedule': 'அட்டவணையை காண்க',
      'weeklyCollectionSchedule': 'வாராந்த அட்டவணை',
      'wasteCollectionHelpText':
          'அட்டவணைகள் உங்கள் பதிவு செய்யப்பட்ட பகுதியை அடிப்படையாகக் கொண்டு காட்டப்படும்.',
      'nextCollection': 'அடுத்த சேகரிப்பு',
      'wasteCollectionUpdated': 'புதுப்பிக்கப்பட்டது',
      'collectionDay': 'சேகரிப்பு நாள்',
      'collectionTime': 'நேரம்',
      'collectionRoute': 'பாதை',
      'collectionNotes': 'குறிப்புகள்',
      'noWasteScheduleYet': 'இதுவரை அட்டவணை இல்லை.',
      'wasteScheduleMissingMessage':
          'உங்கள் உள்ளாட்சி அமைப்பு இந்த பகுதிக்கான அட்டவணையை இன்னும் வெளியிடவில்லை. பின்னர் மீண்டும் பார்க்கவும்.',
      'yourArea': 'உங்கள் பகுதி',
      'refresh': 'புதுப்பி',
      'plannedStops': 'திட்டமிட்ட நிறுத்தங்கள்',
      'appointmentTitle': 'GN சந்திப்பு',
      'appointmentSubtitle':
          'உங்கள் உள்ளூர் கிராம அலுவலரை சந்திக்க நேரத்தை முன்பதிவு செய்யுங்கள்',
      'bookGnAppointment': 'GN சந்திப்பு பதிவு செய்',
      'bookGnAppointmentSubtitle':
          'நேரில் அல்லது தொலைபேசி வழிகாட்டுதலுக்கு ஒரு நேர இடத்தை முன்பதிவு செய்யுங்கள்.',
      'bookAppointmentAction': 'சந்திப்பு பதிவு செய்',
      'appointmentHeroSubtitle':
          'தேதி, நேரம் மற்றும் காரணத்தை தேர்வு செய்யுங்கள். உங்கள் பகுதிக்கான கோரிக்கையை ஒழுங்காக வைத்திருக்கிறோம்.',
      'appointmentFormTitle': 'சந்திப்பு விவரங்கள்',
      'appointmentFormSubtitle':
          'உங்களுக்கு என்ன தேவை மற்றும் எப்போது சந்திக்க விரும்புகிறீர்கள் என்பதை சொல்லுங்கள்',
      'appointmentSubjectLabel': 'சந்திப்பிற்கான காரணம்',
      'appointmentSubjectGeneral': 'பொது சந்திப்பு',
      'appointmentSubjectDocument': 'ஆவண சரிபார்ப்பு',
      'appointmentSubjectLand': 'நிலம் அல்லது முகவரி பிரச்சினை',
      'appointmentSubjectComplaint': 'புகார் பின்தொடர்பு',
      'appointmentSubjectCertificate': 'சான்றிதழ் உதவி',
      'appointmentReasonLabel': 'காரணம்',
      'appointmentReasonHint':
          'பிரச்சினை அல்லது கோரிக்கையை சில வரிகளில் விளக்கவும்',
      'appointmentReasonTooShort':
          'தயவுசெய்து மேலும் விரிவான காரணத்தை உள்ளிடவும்.',
      'selectAppointmentDate': 'சந்திப்பு தேதியை தேர்வு செய்',
      'preferredDate': 'விரும்பிய தேதி',
      'preferredTimeSlot': 'விரும்பிய நேர இடம்',
      'appointmentSlotMorning': 'காலை',
      'appointmentSlotAfternoon': 'மதியம்',
      'appointmentSlotEvening': 'மாலை',
      'appointmentMode': 'சந்திப்பு முறை',
      'appointmentModeInPerson': 'நேரில்',
      'appointmentModePhone': 'தொலைபேசி அழைப்பு',
      'urgentRequest': 'அவசரமாக குறி இடவும்',
      'urgentRequestSubtitle':
          'விஷயம் விரைவான கவனம் தேவைப்படும் போது மட்டும் பயன்படுத்தவும்',
      'additionalNotes': 'கூடுதல் குறிப்புகள்',
      'submitAppointment': 'சந்திப்பை சமர்ப்பி',
      'appointmentSubmitted': 'சந்திப்பு சமர்ப்பிக்கப்பட்டது',
      'appointmentSubmittedMessage': 'உங்கள் சந்திப்பு குறிப்பு எண்',
      'appointmentSubmitFailed': 'சந்திப்பை சமர்ப்பிக்க முடியவில்லை',
      'upcomingAppointments': 'வரவிருக்கும் சந்திப்புகள்',
      'plannedAppointments': 'திட்டமிட்ட சந்திப்புகள்',
      'noAppointmentsYet': 'இதுவரை சந்திப்புகள் இல்லை',
      'appointmentEmptyStateMessage':
          'நீங்கள் ஒரு சந்திப்பை பதிவு செய்ததும், அது இங்கு நிலைமையுடன் தோன்றும்.',
      'cancelAppointment': 'சந்திப்பை ரத்து செய்',
      'appointmentRequiresSignIn': 'சந்திப்பை பதிவு செய்ய உள்நுழைக',
      'appointmentSignInMessage':
          'உங்கள் சந்திப்பு சரிபார்க்கப்பட்ட குடிமகன் சுயவிவரத்துக்கும் பகுதி விவரங்களுக்கும் இணைக்கப்படும்.',
      'appointmentAreaUnknown': 'பகுதி இன்னும் ஏற்றப்படவில்லை',
      'appointmentHelpText':
          'சந்திப்புகள் உங்கள் சரிபார்க்கப்பட்ட சுயவிவரத்துடன் சேமிக்கப்படும், இதனால் அதிகாரி சரியான உள்ளூர் பகுதிக்கான கோரிக்கையை பரிசீலிக்க முடியும்.',
      'scheduledFor': 'நியமிக்கப்பட்ட தேதி',
      'officerNote': 'அதிகாரி குறிப்பு',
      'officerGnAppointmentsTitle': 'GN சந்திப்புகள்',
      'officerGnAppointmentsSubtitle':
          'குடிமக்கள் சந்திப்பு கோரிக்கைகளை மதிப்பாய்வு செய்து நிர்வகிக்கவும்',
      'officerGnInboxTitle': 'GN சந்திப்பு இன்பாக்ஸ்',
      'officerGnInboxDescription':
          'கோரிக்கைகளை மதிப்பாய்வு செய்து புதிய தேதிகளை அமைத்து குடிமக்களுக்கு புதுப்பிப்புகளை வழங்கவும்.',
      'officerScopeAllAreasAdmin': 'வரம்பு: அனைத்து பகுதிகளும் (நிர்வாகி)',
      'officerScopeNoAreaAssigned': 'வரம்பு: பகுதி ஒதுக்கப்படவில்லை',
      'officerScopePrefix': 'வரம்பு',
      'officerStatNew': 'புதியது',
      'officerSearchAppointmentsHint':
          'பெயர், குறிப்பு எண் அல்லது பகுதி மூலம் தேடவும்...',
      'officerAppointmentsFound': 'சந்திப்புகள் கிடைத்தன',
      'officerNoAppointmentsForArea':
          'உங்கள் பகுதிக்கு எந்த சந்திப்பும் கிடைக்கவில்லை.',
      'officerProfileLoadError': 'அதிகாரி சுயவிவரத்தை ஏற்ற முடியவில்லை.',
      'officerAppointmentsLoadError': 'சந்திப்புகளை ஏற்றுவதில் பிழை',
      'officerApproveAppointment': 'சந்திப்பை ஒப்புதல் அளி',
      'officerApproveHint': 'குடிமகனுக்கான விருப்ப குறிப்பு',
      'officerDeclineAppointment': 'சந்திப்பை நிராகரி',
      'officerDeclineHint': 'காரணம் அல்லது அடுத்த படியைச் சேர்க்கவும்',
      'officerMarkCompleted': 'நிறைவு என குறி',
      'officerCompleteHint': 'விருப்ப நிறைவு குறிப்பு',
      'officerAppsReview': 'மதிப்பாய்வு',
      'officerAppsStartReview': 'மதிப்பாய்வை தொடங்கு',
      'officerAppsReject': 'நிராகரி',
      'officerRescheduleAppointment': 'சந்திப்பை மறுநாள் நிர்ணயி',
      'officerRescheduleHint': 'விருப்ப மறுநாள் நிர்ணய குறிப்பு',
      'officerSelectNewDate': 'புதிய சந்திப்பு தேதியைத் தேர்ந்தெடுக்கவும்',
      'officerNewDatePrefix': 'புதிய தேதி',
      'officerAppointmentUpdated': 'சந்திப்பு வெற்றிகரமாக புதுப்பிக்கப்பட்டது',
      'officerAppointmentUpdateFailed': 'சந்திப்பை புதுப்பிக்க முடியவில்லை',
      'statusRequested': 'கோரப்பட்டது',
      'statusApproved': 'ஒப்புதல் அளிக்கப்பட்டது',
      'statusRescheduled': 'மறுநாள் நிர்ணயிக்கப்பட்டது',
      'statusDeclined': 'நிராகரிக்கப்பட்டது',
      'actionApprove': 'ஒப்புதல்',
      'actionReschedule': 'மறுநாள் நிர்ணயி',
      'actionDecline': 'நிராகரி',
      'actionMarkCompleted': 'நிறைவு என குறி',
      'change': 'மாற்று',
      'seeAll': 'அனைத்தையும் காண்க',
      'noActiveApplicationsYet': 'இன்னும் செயலில் விண்ணப்பங்கள் இல்லை',
      'startFirstRequest':
          'அங்கீகாரம் மற்றும் முன்னேற்றத்தை பார்க்க உங்கள் முதல் கோரிக்கையை தொடங்குங்கள்.',
      'applyNow': 'இப்போது விண்ணப்பிக்கவும்',
      'secureDocs': 'பாதுகாப்பான ஆவணங்கள்',
      'fastUpdates': 'வேகமான புதுப்பிப்புகள்',
      'verifiedService': 'சரிபார்க்கப்பட்ட சேவை',
      'myApplicationsTitle': 'என் விண்ணப்பங்கள்',
      'myApplicationsSubtitle':
          'நிலையும் முன்னேற்றமும் நேரடியாக கண்காணிக்கவும்',
      'everythingInOnePlace': 'எல்லாம் ஒரே இடத்தில்',
      'monitorSubmissionsProgress':
          'சமர்ப்பிப்புகள், முன்னேற்றம் மற்றும் நிறைவு புதுப்பிப்புகளை உடனே காண்க.',
      'noApplicationsFound': 'விண்ணப்பங்கள் எதுவும் இல்லை',
      'viewDetails': 'விவரங்களை காண்க',
      'all': 'அனைத்து',
      'completed': 'முடிந்தது',
      'rejected': 'நிராகரிக்கப்பட்டது',
      'pendingAction': 'நிலுவையில் உள்ள செயல்',
      'submitted': 'சமர்ப்பிக்கப்பட்டது',
      'verified': 'சரிபார்க்கப்பட்டது',
      'processing': 'செயலாக்கம்',
      'finalizing': 'இறுதிப்படுத்தல்',
      'done': 'முடிந்தது',
      'appliedOn': 'விண்ணப்பித்த தேதி',
      'complaintsSubtitle':
          'பிரச்சினைகள் மற்றும் பதில்களை நேரடியாக கண்காணிக்கவும்',
      'pastComplaints': 'முந்தைய புகார்கள்',
      'raiseIssuesCleanly': 'பிரச்சினைகளை தெளிவாக பதிவு செய்யுங்கள்',
      'complaintsHeroSubtitle':
          'புகார்களை சமர்ப்பித்து, புதுப்பிப்புகளை கண்காணித்து, தீர்வு முன்னேற்றத்தை பின்தொடருங்கள்.',
      'lodgeNewComplaint': 'புதிய புகாரை பதிவு செய்',
      'noComplaintsFound': 'புகார்கள் எதுவும் இல்லை',
      'lastUpdatedOn': 'கடைசியாக புதுப்பிக்கப்பட்டது',
      'category': 'வகை',
      'status': 'நிலை',
      'updated': 'புதுப்பிக்கப்பட்டது',
      'close': 'மூடு',
      'open': 'திறந்தது',
      'inspected': 'பரிசோதிக்கப்பட்டது',
      'closed': 'மூடப்பட்டது',
      'submittedSuccessTitle': 'சமர்ப்பிக்கப்பட்டது!',
      'complaintSubmittedMessage':
          'உங்கள் புகார் வெற்றிகரமாக பதிவு செய்யப்பட்டது. குறிப்பு எண்:',
      'backToHome': 'முகப்பிற்கு திரும்பு',
      'newComplaintTitle': 'புதிய புகார்',
      'newComplaintSubtitle':
          'பிரச்சினை விவரங்களை பகிர்ந்து சில படிகளில் சமர்ப்பிக்கவும்',
      'issueCategory': 'பிரச்சினை வகை',
      'complaintTitle': 'புகார் தலைப்பு',
      'detailedDescription': 'விரிவான விளக்கம்',
      'location': 'இடம்',
      'reviewDetails': 'விவரங்களை சரிபார்',
      'notSelected': 'தேர்வு செய்யப்படவில்லை',
      'title': 'தலைப்பு',
      'submitAccuracyNotice':
          'சமர்ப்பிப்பதன் மூலம், வழங்கிய தகவல் துல்லியமானது என்பதை ஒப்புக்கொள்கிறீர்கள்.',
      'previous': 'முந்தையது',
      'submitComplaint': 'புகாரை சமர்ப்பி',
      'continue': 'தொடரவும்',
      'error': 'பிழை',
      'saving': 'சேமிக்கப்படுகிறது...',
      'errorUpdatingProfile': 'சுயவிவரம் புதுப்பிப்பதில் பிழை',
      'failedToUpdateLanguage': 'மொழியை புதுப்பிக்க முடியவில்லை',
      'userName': 'பயனர் பெயர்',
      'nicId': 'NIC / ID',
      'enterYourFullName': 'உங்கள் முழுப்பெயரை உள்ளிடவும்',
      'enterYourPhoneNumber': 'உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்',
      'nicCannotBeChanged': 'NIC மாற்ற முடியாது',
      'loadingUserInformation': 'பயனர் தகவல் ஏற்றப்படுகிறது...',
      'role': 'பங்கு',
      'division': 'பிரிவு',
      'administrativeArea': 'நிர்வாக பகுதி',
      'province': 'மாகாணம்',
      'district': 'மாவட்டம்',
      'pradeshiyaSabha': 'பிரதேச சபை',
      'gramasewaWasama': 'கிராம சேவகர் பிரிவு',
      'selectProvince': 'மாகாணத்தை தேர்வு செய்',
      'selectDistrict': 'மாவட்டத்தை தேர்வு செய்',
      'selectPradeshiyaSabha': 'பிரதேச சபையை தேர்வு செய்',
      'selectGramasewaWasama': 'கிராம சேவகர் பிரிவை தேர்வு செய்',
      'enterPradeshiyaSabha': 'பிரதேச சபை பெயரை உள்ளிடவும்',
      'enterGramasewaWasama': 'கிராம சேவகர் பிரிவு பெயரை உள்ளிடவும்',
      'pleaseSelectAdministrativeArea':
          'தயவு செய்து மாகாணம், மாவட்டம், பிரதேச சபை மற்றும் கிராம சேவகர் பிரிவை தேர்வு செய்யவும்.',
      'loadingAdministrativeAreas': 'நிர்வாக பகுதிகள் ஏற்றப்படுகின்றன...',
      'complaintTitleHint': 'உதா: முக்கிய சாலைக்கு அருகில் உடைந்த நீர்க்குழாய்',
      'describeIssueInDetail': 'பிரச்சினையை விரிவாக விவரிக்கவும்...',
      'locationHint': 'தெரு பெயர் அல்லது அடையாள இடம் உள்ளிடவும்',
      'sortBy': 'வரிசைப்படுத்து',
      'newestFirst': 'புதியவை முதலில்',
      'oldestFirst': 'பழையவை முதலில்',
      'sortStatus': 'நிலை',
      'highestPriority': 'அதிக முன்னுரிமை',
      'anyPriority': 'எந்த முன்னுரிமையும்',
      'priorityFirst': 'முன்னுரிமை முதலில்',
      'officerComplaintsSearchHint':
          'தலைப்பு, பகுதி, வகை அல்லது அடையாள எண்ணின் மூலம் தேடவும்',
      'officerScopeDataQualityCheck': 'தரத் தரவு சரிபார்ப்பு',
      'officerAppsMissingAreaTags':
          'சில GN விண்ணப்பங்களில் குடிமக்கள் பகுதி குறிச்சொற்கள் இல்லை.',
      'officerComplaintsMissingLocationTags':
          'சில புகார்களில் இடம் குறிச்சொற்கள் இல்லை.',
      'officerScopeFallbackDisabledNotice':
          'பரப்பு fallback இயல்பாக முடக்கப்பட்டுள்ளது; நம்பகமான பகுதி வழிமுறை கிடைக்க onboarding பகுதி வரைபாட்டை நிறைவு செய்யவும்.',
      'officerReviewNoPayloadFound':
          'இந்த கோரிக்கைக்கு சமர்ப்பிக்கப்பட்ட payload புலங்கள் எதுவும் கிடைக்கவில்லை.',
      'officerReviewNoDocumentsFound':
          'இந்த விண்ணப்பத்திற்கு பதிவேற்றப்பட்ட ஆவணங்கள் எதுவும் கிடைக்கவில்லை.',
      'officerReviewInvalidDocumentUrl': 'தவறான ஆவண URL.',
      'officerReviewOpenDocumentFailed': 'ஆவண இணைப்பை திறக்க முடியவில்லை.',
      'safetyRiskFirst': 'பாதுகாப்பு அபாயம் முதலில்',
      'priority': 'முன்னுரிமை',
      'landmark': 'அடையாள இடம்',
      'incidentDateTime': 'சம்பவ தேதி/நேரம்',
      'safetyRisk': 'பாதுகாப்பு அபாயம்',
      'anonymous': 'அடையாளம் வெளிப்படாதது',
      'followUpAllowed': 'பின்தொடர்பு அனுமதி',
      'preferredContact': 'விருப்பமான தொடர்பு முறை',
      'phone': 'தொலைபேசி',
      'email': 'மின்னஞ்சல்',
      'affectedPeople': 'பாதிக்கப்பட்ட மக்கள்',
      'description': 'விளக்கம்',
      'additionalDetails': 'கூடுதல் விவரங்கள்',
      'yes': 'ஆம்',
      'no': 'இல்லை',
      'low': 'குறைவு',
      'medium': 'நடுத்தரம்',
      'high': 'உயர்',
      'critical': 'அவசரம்',
      'pleaseSelectService': 'தொடர சேவையைத் தேர்ந்தெடுக்கவும்',
      'serviceNotFound': 'சேவை காணப்படவில்லை',
      'pleaseFillIn': 'தயவுசெய்து பூர்த்தி செய்யவும்',
      'pleaseUpload': 'தயவுசெய்து பதிவேற்றவும்',
      'serviceApplicationTitle': 'சேவை விண்ணப்பம்',
      'serviceApplicationSubtitle':
          'விவரங்களை சமர்ப்பித்து ஒரே நடைமுறையில் கட்டணத்தை முடிக்கவும்',
      'step': 'படி',
      'of': 'இல்',
      'selectGovernmentService': 'அரசு சேவையைத் தேர்ந்தெடுக்கவும்',
      'serviceSelectionSubtitle':
          'ஒவ்வொரு சேவைக்கும் தனித்துவமான தேவைகள் மற்றும் காலவரையறை உள்ளது',
      'serviceTypeNotFound': 'சேவை வகை கிடைக்கவில்லை',
      'serviceDetails': 'சேவை விவரங்கள்',
      'requiredDocuments': 'தேவையான ஆவணங்கள்',
      'uploadRequiredDocumentsNote':
          'பின்வரும் ஆவணங்களின் டிஜிட்டல் நகல்களை பதிவேற்றவும்:',
      'upload': 'பதிவேற்று',
      'uploadFailed': 'பதிவேற்றம் தோல்வியடைந்தது',
      'uploaded': 'பதிவேற்றப்பட்டது ✓',
      'uploading': 'பதிவேற்றப்படுகிறது...',
      'changeFile': 'கோப்பை மாற்று',
      'browseFiles': 'கோப்புகளை தேடு',
      'reviewAndConfirm': 'சரிபார்த்து உறுதிப்படுத்து',
      'service': 'சேவை',
      'submittedInformation': 'சமர்ப்பிக்கப்பட்ட தகவல்',
      'applicationSubmittedAfterPayment':
          'வெற்றிகரமான கட்டணத்திற்குப் பிறகே விண்ணப்பம் சமர்ப்பிக்கப்படும்',
      'proceedToPayment': 'கட்டணத்திற்கு செல்லவும்',
      'paymentCancelled': 'கட்டணம் ரத்து செய்யப்பட்டது',
      'paymentError': 'கட்டண பிழை',
      'paymentSuccessful': 'கட்டணம் வெற்றிகரமாக முடிந்தது!',
      'paymentSuccessMessagePrefix':
          'உங்கள் கட்டணம் வெற்றிகரமாக செயலாக்கப்பட்டது, விண்ணப்பமும் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது.',
      'transactionId': 'பரிவர்த்தனை ஐடி',
      'checkout': 'கட்டண நிறைவு',
      'securePaymentViaPayHere': 'PayHere மூலம் பாதுகாப்பான கட்டணம்',
      'paymentSetupMissing': 'கட்டண அமைப்பு இல்லை',
      'serverError': 'சேவையக பிழை',
      'signInToGovEase': 'GovEase இற்கு உள்நுழைக',
      'chooseAccessTypeSubtitle':
          'உங்கள் அணுகல் வகையைத் தேர்ந்து பாதுகாப்பாக தொடரவும்',
      'officer': 'அதிகாரி',
      'dontHaveAccount': 'கணக்கு இல்லையா? ',
      'nicExampleLong': 'உதா: 199512345678',
      'nicFormatHint': 'NIC வடிவம்: 12 இலக்கங்கள் அல்லது 9 இலக்கங்கள் + V/X',
      'phoneExample': 'உதா: 077 123 4567',
      'phoneFormatHint': '10 இலக்க உள்ளூர் எண்ணை பயன்படுத்தவும் (07XXXXXXXX)',
      'codeSentTo': 'குறியீடு அனுப்பப்பட்டது',
      'otpPlaceholder': '------',
      'changeNumber': 'எண்ணை மாற்று',
      'officerId': 'அதிகாரி ஐடி',
      'officerIdExample': 'உதா: GN-2024-0147',
      'verificationMethod': 'சரிபார்ப்பு முறை',
      'password': 'கடவுச்சொல்',
      'otp': 'OTP',
      'enterPassword': 'கடவுச்சொல்லை உள்ளிடவும்',
      'tapSignInSendOfficerOtp':
          'பதிவுசெய்யப்பட்ட அதிகாரி மொபைல் எண்ணிற்கு OTP அனுப்ப Sign In அழுத்தவும்.',
      'otpDigitsPlaceholder': '000000',
      'sendOtpAndContinue': 'OTP அனுப்பு & தொடரவும்',
      'signInAsOfficer': 'அதிகாரியாக உள்நுழைக',
      'authorizedOfficersNotice':
          'அங்கீகரிக்கப்பட்ட அரசு அதிகாரிகளுக்கு மட்டும். அனைத்து செயல்களும் பதிவு செய்யப்படும்.',
      'verificationFailedMessage':
          'சரிபார்ப்பு தோல்வியடைந்தது. குறியீடு மற்றும் எண் சரியா என்பதைச் சரிபார்க்கவும்.',
      'otpResentSuccess':
          'OTP மீண்டும் அனுப்பப்பட்டது! உங்கள் தொலைபேசியைப் பாருங்கள்.',
      'failedToResendOtp':
          'OTP மீண்டும் அனுப்ப முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
      'verificationFailed': 'சரிபார்ப்பு தோல்வி',
      'signInFailed': 'உள்நுழைவு தோல்வி',
      'verifyIdentity': 'அடையாளத்தைச் சரிபார்',
      'signupSubtitle':
          'GovEase சமூகத்தில் சேர்ந்து அரசு சேவைகளை எளிதாகப் பெறுங்கள்',
      'otpEntrySubtitle':
          'உங்கள் மொபைலிற்கு அனுப்பப்பட்ட 6 இலக்க குறியீட்டை உள்ளிடவும்',
      'verify': 'சரிபார்',
      'alreadyHaveAccount': 'ஏற்கனவே கணக்கு உள்ளதா? ',
      'nameExample': 'உதா: John Doe',
      'resendAvailableIn': 'மீண்டும் அனுப்ப கிடைக்கும் நேரம்',
      'sending': 'அனுப்பப்படுகிறது...',
      'didntReceiveCodeResend': 'குறியீடு வரவில்லையா? மீண்டும் அனுப்பு',
      'info': 'தகவல்',
    },
  };

  String tr(String key) {
    final languageMap =
        _localizedValues[locale.languageCode] ?? _localizedValues['en']!;
    return languageMap[key] ?? _localizedValues['en']![key] ?? key;
  }
}

extension AppLocalizationExtension on BuildContext {
  String tr(String key) {
    final languageCode = Localizations.localeOf(this).languageCode;
    return AppLocalizations(Locale(languageCode)).tr(key);
  }
}
